### ISSUE TITLE
Does Sugar work with Views?

### ISSUE THREAD

**Issue by shawnhwei** [chennaione/sugar#334]
Title.

**Comment by black-snow** [comment]
What do you mean by "Does Sugar work with Views"?

Databinding? No. Not out of the box (afaik).

**Comment by meetshawn** [comment]
I meant SQL views aka virtual tables.

**Comment by black-snow** [comment]
Haven't tried yet. I don't know how / if sugar works w/ tables it didn't create itself. I'd say "give it a try".
If sugar works w/ custom tables it shoul run fine on views, too (as long as you don't save anything).
