### ISSUE TITLE
Allow usage without manifest configuration

### ISSUE THREAD

**Issue by andrewpros** [chennaione/sugar#596]
Hi.

The title says it all, i don't want to place the name of my database in manifest, i don't want to place anything more that is needed there.

But there is no way to set in it code, the issue is here https://github.com/satyan/sugar/blob/master/library/src/main/java/com/orm/helper/ManifestHelper.java#L77

No way to set DATABASE_DEFAULT_NAME programmatically.

Yet i don't see any reason why to force adding manifest configuration.

Please consider this.

**Comment by papagno** [comment]
It would be nice and it would make multiple db possible in the future.

**Comment by andrewpros** [comment]
Yeah, fixed it simple, removed the final from DATABASE_DEFAULT_NAME and now i can set it easy.

**Comment by CampsiteHelper** [comment]
+1 silly to need application inherit as well.

**Comment by lauborges** [comment]
+1

**Comment by cutiko** [comment]
I have to disagree with this, if you compare to other ORMs that dont do this, then everything must be setup manually.This would mean to kill what make Sugar ORM great, zero boiler plate code. Look at other ORMs and check how much trash you have to write to create a table. Sugar setup is fine, is unusual, but as long as I dont have to do stupid thinks like declaring each variable inside a model with an annotation, I rather this than any other.

**Comment by andrewpros** [comment]
You are wrong, if i need to modify the source code to even make it work for my project as is should from the beginning, then it is not good.

Functions that should be essential are missing.

Problem is it works fine if you use it with the default usage developers thought about, but not if you just making something else, eg. not creating single blank  database managed completely by the ORM.

For now you can't even use multiple dbs.

"zero boiler plate code" aside from the forced manifest edits?

"as long as I dont have to do stupid thinks like declaring each variable inside a model with an annotation" and this is exactly what i need to do now, cuz sugar is always forcing its columns naming scheme, but i already have a scheme and an existing db that is a part of larger system and it can't be changed, nor that a ORM should force you to change anything even if you can.

My changes would make sugar the best and simple ORM on android, for EVERY project not only intended usage by the developers, cuz this should be an ORM, a universal solution.

**Comment by cutiko** [comment]
@andrewpros according to your explanation then the problem is **Sugar doesnt fit your project**. There is no shame on asking, but I wont consider fair to ask a developer team to change their open source library to fit my project.

**Comment by satyan** [comment]
@andrewpros thanks for your suggestions. Working with existing database is an issue right now. What are some other thoughts that you feel could improve this case?

Manifest metadata was intended to externalize these settings, and works for fresh development. However, we'd like to enable some advance features as well alongside it. 

Thanks for your feedback.

**Comment by andrewpros** [comment]
@cutiko 
You are misinterpreting things, ORM needs to be universal, this is the whole point of an ORM, it is not that it doesn't fit my project, my project could be yours, could be anybody's project that needs ORM.

And guess what, people have different projects, different usage scenarios, different ideas, needs, specifications...

If you tell me that those all people should rewire their code, change their dbs tables, columns, they way they planed things, change their ideas, adjust it to a library then you are plain and simple wrong. Such thing would mean every project needs to make every thing the same way, no exceptions, you can do it the library way or go away, that's not serious attitude.

It is the library that should be universal to fit any project that needs ORM, not the way around, this is why it is called ORM, from the definition it should only map database to code, what you do with it it only your call.

But right now, you can't do anything you want with sugar, you need to change the source.

If people were to listen you all project should be the same, you argument is invalid.

I choose to mention this concerns about sugar ORM, cuz in my opinion it is the closest project to a perfection, it is really simple to setup and just works like that comparing to other contenders and i have made extensive reviews.

So i know what i'm talking about.
