### ISSUE TITLE
Can't use any primary key name?

### ISSUE THREAD

**Issue by andrewpros** [chennaione/sugar#597]
Hi.

So let's me get this straight, i can't use any table schema i want? I mean use any primary key id name i want?

This is unacceptable. I was looking for a simple orm solution, but it isn't.

I was fighting it for hours, i want to use it on a existing database that will be downloaded from internet.

Problems started with only camel case table names in query, ok i found i need to use table name annotation on entity names.

Then it started to return 0 records, but the data was there.

I have pinpoint it to this https://github.com/satyan/sugar/blob/master/library/src/main/java/com/orm/SugarRecord.java#L361

So if my database table does not have a primary long key with name ID it won't work?

I keep getting java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.

And there is no workaround now, the "ID" is hardcoded (and need to be UPPERCASE), i don't get, why the ORM forces me to use specific primary key when it uses refection anyway?

The ORM library should be compatible with databases not the other way around, won't you say?

Now im frustrated, cuz there are no workaround, and i need to ditch it, time wasted.

Are you planning to fix it? Or maybe there is a workaround?

In my use case i can change the tables ids, they have different names like pk_i_id and there are not always long, just int.

It is a part of larger system and the need to be compatible.

**Comment by andrewpros** [comment]
Does anyone is supporting this ORM or not? Is it dead for good?

**Comment by sibeliusseraphini** [comment]
this PR https://github.com/satyan/sugar/pull/556 should address this

**Comment by andrewpros** [comment]
Well, for the time being i just made PK annotation with name just like table and a fix for https://github.com/satyan/sugar/blob/master/library/src/main/java/com/orm/SugarRecord.java#L361 just checking the PK annotation name.

Don't have time to wait for PR that god knows when will be released. Such things should be made long ago. Still great project to base on, hance i still want to use it, could be close to perfect with some changes.

And sadly this PR won't fix a thing based on the changes.

And i can't say that sugar is universal, it favors SINGLE database usage, MANIFEST CONFIGURATION, CREATING NEW DATABASE use cases not using existing ones and INVERTED DEFAULT approach.

But an ORM should be universal and cover all needs, not forcing some "rules"

- SINGLE db, you can't change the db when you want, no programmatic way to change db name or use another
- MANIFEST config, again not needed, should be optional, anything in manifest must be configurable in code also
- CREATING NEW DB, that's just the filling, more like ORM to create and use new db than universal way to use any db, new or existing or/and multiple ones, also other design decision shows that, like default naming scheme
- INVERTED default approach, an ORM should use the default names from user provided classes without annotation and without forcing it own table or column naming scheme as the default one, what is the point if it isn't plug and play and i needed to create a class for table and then duplicate the same names in column annotation and table? Just cuz the names scheme was forced by default.

And i'm 100% sure that most people won't have a DB with such column names as sugar schema, so they will need to use annotation.

But there it the PK, can't change that folks.

From the linked PR i can see it won't be better, adding another MANIFEST option for PK ID name? Why, where is sense in this? Any table can have different pk id name.

Just don't force people to change anything, most need, a plug and play ORM, that support single or many db usage, new or existing, without any xml config, than can do anything and configure programmatically and don't force any naming of table and columns.

Just an universal ORM that don't put strings on them and forces to change their db designs.

**Comment by sibeliusseraphini** [comment]
@andrewpros thanks for your descriptions of sugar current problems

could you please provide one PR for each one of the issues pointed out? I will be glad to review it

**Comment by andrewpros** [comment]
I would be glad to, but sadly for now i just don't have time more than make simple fixes for my own project, i have removed final from DATABASE_DEFAULT_NAME so i can set it before sugardb init and i also have made said PK annotation to overcome the primary ID naming issue.

And for the inverted default i just had to make table classes and duplicate again every column name to a column annotation, again to overcome the default sugar ORM naming issues.

And i have only 10 tables with about 50 columns total, was not quick but faster that fixing the code, but what if someone has 20 tables and 200 columns and it is just a mirror of another database from some larger system that needs to be column compatible so no no for any changes.
