### ISSUE TITLE
SugarOrm not working for gradle version more than 2.0

### ISSUE THREAD

**Issue by deeppandya** [chennaione/sugar#612]
when i use SugarOrm with gradle version 1.5 it's working perfectly fine. but if i use with gradle version 2.0 and above. it's not working. 

Could you please check it ?

Thanks

**Comment by JonatanSalas** [comment]
What is the error that you receive when trying to run a build? Could you post the entire stacktrace?

**Comment by cutiko** [comment]
Please read this thread https://github.com/satyan/sugar/issues/613#issuecomment-223300514 if it is your problem, hot fix seems to be on the way, anyway try the options propossed there

**Comment by larrytech7** [comment]
My gradle version is 2.1.3 and am using sugar 1.5 .Everything is stable
