### ISSUE TITLE
Function "countWithQuery"

### ISSUE THREAD

**Issue by felipebonezi** [chennaione/sugar#661]
Sometimes is useful to call Count Function with a query associated with - e.g. `"SELECT count(*) FROM quiz q LEFT JOIN image i ON i.quiz_id = q.id WHERE i.url IS NOT NULL;"`

If some one instruct me a while, I can make it by my self and do a Pull Request. :-)

**Comment by sibelius** [comment]
U can do this using this function

https://github.com/satyan/sugar/blob/master/library/src/main/java/com/orm/SugarRecord.java#L254

lmk if this works or not

**Comment by felipebonezi** [comment]
@sibelius did you see that my SQL has `Join Association`?
How can I use `count(Class, String, String)` for my example?

**Comment by sibelius** [comment]
`count` method will generate: `SELECT count(*) FROM quiz where` + whereClause

so I think u should overload `count` method to use it with a JOIN query
