### ISSUE TITLE
Function "findWithQuery" return a specific list of Columns

### ISSUE THREAD

**Issue by felipebonezi** [chennaione/sugar#662]
Is there any solution for this SQL? 
`Quiz.findWithQuery(Quiz.class, "SELECT q.id FROM quiz q;", null);`

Every time is return a SQLException in `inflate()` from Sugar class.

**Comment by sibelius** [comment]
could u inspect ur database to see if quiz has an `id` field?

**Comment by larrytech7** [comment]
why are you using q.id instead of quiz.id or simpy id. Does your quiz table have an id field?

**Comment by felipebonezi** [comment]
Well, this's a basic SQL, the complex one use `JOIN` with other tables.
I assume that a `SugarRecord` have a `id` field, so I used this identifier.

Am I wrong?
