### ISSUE TITLE
Disappointing getting started moments

### ISSUE THREAD

**Issue by adrianrobotka** [chennaione/sugar#727]
Hello,
I'm new around Sugar ORM.
I've tried to use this (I went throw the docs https://satyan.github.io/sugar/getting-started.html properly) and I wasn't able to use the ORM for 2 hours because of the issue #613 (I use the latest Android Studio)
I suggest to update the documentation to prevent the further disappointing getting-started moments for others just because of instant-run functionality of the Android Studio.

**Comment by refaelsh** [comment]
+1

**Comment by ibewugb** [comment]
What exact sulution out of #613 did you use to get it running?

**Comment by adrianrobotka** [comment]
Personally, I turned off Android Studio "Instant Run" functionality. And after that the ORM worked fine.
