### ISSUE TITLE
I want list result does not have a id column

### ISSUE THREAD

**Issue by TonyJason** [chennaione/sugar#740]
hello ,I use code:
Gson gson= new Gson();
List<UserLog> userLogs = UserLog.listAll(UserLog.class);
List<UserLog> userList = gson.fromJson(gson.toJson(userLogs), new TypeToken<List<UserLog>>() {
        }.getType());
JsonArray jsonArray = new Gson().toJsonTree(userList, new TypeToken<List<UserLog>>() {
        }.getType()).getAsJsonArray();
Log.e(TAG,jsonArray);
run after ,the result log is:
[{"time":"2017-04-17 17:43:50","crawl_book_id":245781,"chapter_id":48473,"id":1}]
But I want list result does not have a id column like 
[{"time":"2017-04-17 17:43:50","crawl_book_id":245781,"chapter_id":48473}]
how should I do ? Thank you

**Comment by kigen** [comment]
The trick here is to use GSON exclusion strategy: which is just a way to instruct GSON to skip certain fields/classes during de/serialization: In this case Serialization.
To read more on exclusion strategies check this article: 
https://google.github.io/gson/apidocs/com/google/gson/ExclusionStrategy.html

Here is a simple example on how to implement Exclusion strategy for your project. 

```
public static class Exclude implements ExclusionStrategy {

        public Exclude() {
            super();
        }

        @Override
        public boolean shouldSkipClass(Class<?> arg0) {
            return false;
        }

        /**
         * Criteria for Skipping a field.
         *
         * @param field The field to be evaluated for skipping.
         * @return True/False - Whether the field should be skipped or not.
         */
        @Override
        public boolean shouldSkipField(FieldAttributes field) {
            if(field.getName().equals("id")){
               return true;
            }
            return false;
        }
    }
```
Create an instance of gson this way: 
```
 Gson gson = new GsonBuilder().addSerializationExclusionStrategy(new Exclude()).create();
```
Now use ```gson```  to serialize your list of users and the JSON output should now skip serializing the id field.

**Comment by TonyJason** [comment]
Thank you, I  use  your method, I solve the problem!

**Comment by JonatanSalas** [comment]
@TonyJason I will close this issue since you've already solved the problem!
